export default {
  ADD_SPOT: 'ADD_SPOT',
  RECEIVE_SPOTS: 'RECEIVE_SPOTS',
  MAP_STATE_CHANGE: 'MAP_STATE_CHANGE',
  REQUEST_SPOTS: 'REQUEST_SPOTS',
  SPOT_SELECTED_ON_MAP: 'SPOT_SELECTED_ON_MAP',

}
